<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$ciencia = [
"titulo" => "PRIMER ESTACION ESPACIAL EN PERU",
"autor" => "EL COMERCIO",
"resumen" => "PRIMERA ESTACION ESPACIAL EN LATAM",
];
?>
