<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$cultura = [
"titulo" => "LA GRAN MARAVILLA DEL MUNDO CUZCO",
"autor" => "LEON CARLO",
"resumen" => "MACCHU PICCHU",
];
?>
