<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$deportes = [
"titulo" => "LA LIGA PERUANA ACUSADA DE ROBO ARBITRARIO A LOS EQUIPOS LOCALES DE CHIMBOTE",
"autor" => "RPP NOTICIAS",
"resumen" => "SE ENCONTRARON IRREGULARIDADES EN EL EQUIPO ATLETICO BRUCES",
];
?>
