<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$empleo = [
"titulo" => "SOLICITUD EN LA BOLSA DE TRABAJO DE LA UNS ",
"autor" => "UNIVERSIDAD NACIONAL DEL SANTA",
"resumen" => "SE SOLICITA ALUMNOS EGRESADOS CON BACHILLER AUTOMATICO PARA LOS PUESTOS DENTRO DE LA UNIVERSIDAD",
];
?>
