<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$formacion = [
"titulo" => "AMPLIA LEY DE BACHILLER AUTOMATICO",
"autor" => "Gabinete de comunicación",
"resumen" => "EL MINISTERIO DE EDUCACION JUNTO CON EL CONGRESO DE LA REPUBLICA AMPLIA EL ESTADO DE BACHILLER AUTOMATICO HASTA EL 2026",
];
?>
