<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$nacional = [
"titulo" => "DECRETA ETADO DE EMERGENCIA EN SJL",
"autor" => "DIARIO EL TROME",
"resumen" => "INREMENTO DE CASOS DE SICARIATO Y HOMICIDIO DURANTE ESTAS 2 ULTIMAS SEMANAS",
];
?>
