<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$openshift = [
"titulo" => "DISTRIBUCION DE LINUX",
"autor" => "LINUX",
"resumen" => "PARTE DE LA DISTRIBUCION DE RED HAT",
];
?>
