<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$sociedad = [
"titulo" => "SOCIEDAD PRIVADA DEL NORTE ",
"autor" => "EL DIARIO EL CONGRESO",
"resumen" => "SOCIEDAD PERUANA",
];
?>
