<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$tecnologia = [
"titulo" => "SPRING BOOT EL NUEVO ALCNAZE DE LAS TECNOLOGIAS",
"autor" => "JAVA ENTERPRISE",
"resumen" => "SE UTILZIA PARA EL BACKEND",
];
?>
